version: "3.7"
services:
  postgres:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_PASSWORD=test_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    expose: [5432]

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli PING"]
      interval: 10s
      timeout: 5s
      retries: 5

  ganache:
    build:
      dockerfile: Dockerfile.ganache
      context: docker
    ports:
      - "8545:8545"

  ws-engine:
    build:
      context: modules
      dockerfile: ../docker/Dockerfile.ws-engine
    ports:
      - "5001:5001"
    expose:
      - "5001"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FASTIFY_PORT=5001
      - FASTIFY_ADDRESS=0.0.0.0
    depends_on: [eth-engine]

  eth-engine:
    build:
      context: modules
      dockerfile: ../docker/Dockerfile.eth-engine
    network_mode: host
    environment:
      - REDIS_HOST=0.0.0.0
      - REDIS_PORT=6379
      - WEBSOCKET_URL=ws://0.0.0.0:8545
    depends_on:
      - ganache
      - redis
